"""add_comments_table

Revision ID: a8340df326db
Revises: 001
Create Date: 2026-05-19 06:53:46.969503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8340df326db'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task_service.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='task_service'
    )
    op.create_index(op.f('ix_task_service_comments_task_id'), 'comments', ['task_id'], unique=False, schema='task_service')
    op.drop_index('ix_task_service_tasks_status', table_name='tasks', schema='task_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_task_service_tasks_status', 'tasks', ['status'], unique=False, schema='task_service')
    op.drop_index(op.f('ix_task_service_comments_task_id'), table_name='comments', schema='task_service')
    op.drop_table('comments', schema='task_service')
    # ### end Alembic commands ###



